
---
- name: Configure DevOps Master
  hosts: master
  become: yes

  tasks:
    - name: Remove old broken Jenkins repo
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Remove old Jenkins key
      file:
        path: /usr/share/keyrings/jenkins-keyring.asc
        state: absent

    - name: Install basic packages
      apt:
        name:
          - curl
          - gnupg
          - fontconfig
          - openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Add Jenkins repo key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key -o /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

- name: Configure Build Agent
  hosts: build
  become: yes

  tasks:
    - name: Install Java and Docker
      apt:
        name:
          - openjdk-21-jdk
          - docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
